### ISSUE TITLE
.DS_store

### ISSUE THREAD

**Issue by Goolgae** [songyouhyun/Notice-Board#1]
> `.DS_store`는 맥에서 finder으로 디렉터리를 왔다갔다 했을때 생기는 파일

`.gitignore`에 `.DS_*`을 넣어주시면 해결되지만 이미 원격저장소에 올라가져있기 때문에

아래와 같이 캐쉬를 삭제한후에 넣어주시면 됩니다.

```zsh
git rm -r --cached .
git add .
git commit -m "Clear git cache"
```

**Comment by Goolgae** [comment]
이제 보니 `.gitignore`가 없네요! 파일 추가하면됩니다.

[참고하면 좋은 자료](https://nesoy.github.io/articles/2017-01/Git-Ignore)

**Comment by songyouhyun** [comment]
감사합니👍

**Comment by Goolgae** [comment]
*^^*
